### ISSUE TITLE
Consider also managing the DNS Records

### ISSUE THREAD

**Issue by FrederikNS** [tazjin/kubernetes-letsencrypt#38]
Hi, I just tried out this project in our cluster, and it worked flawlessly. The only thing I feel is missing was that kubernetes-letsencrypt could also provision the actual DNS record.

It seems the project has everything that is needed, as it already creates the _acme-challenge DNS record, so I hope it wouldn't be too tricky.

**Comment by tazjin** [comment]
Hey, glad to hear that! :) 

I've been considering this but I sort of see it as a separate concern, so it feels like it shouldn't be part of the Let's Encrypt controller.

My thinking is that it should be a separate DNS controller, but I know that Kubernetes itself is working on support for record-provisioning - though I haven't seen a proposal for how to handle multiple domains there.

Would be interested in hearing your thoughts on this. We need something managing those records at my current project so I'll be implementing a solution either way.

**Comment by FrederikNS** [comment]
I agree that maybe it's a separate concern, I tried using [route53-kubernetes](https://github.com/wearemolecule/route53-kubernetes) for provisioning the DNS records, but ran into issues as our DNS HostedZones are nested, and the route53-kubernetes project unfortunately just adds the record in the first matching HostedZone, instead of the most specific HostedZone.

I have also put in an issue for route53-kubernetes here: wearemolecule/route53-kubernetes#27

**Comment by tazjin** [comment]
Hmm, interesting. I have [some logic](https://github.com/tazjin/kubernetes-letsencrypt/blob/master/src/main/java/in/tazj/k8s/letsencrypt/acme/Route53Responder.java#L81) for finding the most specific zone instead, though you just made me think that maybe people want to be able to override that as well.

I'll consider making a separate `kubernetes-dns-controller`. As you said large portions of the code are already here so it should be quite reusable.

**Comment by ensonic** [comment]
I can recommend external-dns for managing the dns record: https://github.com/kubernetes-incubator/external-dns

**Comment by tazjin** [comment]
I think `external-dns` (as @ensonic linked above) is the correct solution to this, either way it shouldn't be part of this particular controller so I'm closing the issue.
