### ISSUE TITLE
 DnsException: Insufficient Permission

### ISSUE THREAD

**Issue by TheMalloum** [tazjin/kubernetes-letsencrypt#58]
Hi,

I grants to the "DNS Administrator" rights the account use.
This account is find with the "gcloud info" command.
Is it correct ?

**Comment by TheMalloum** [comment]
Hi,

I switch from a v1.6 branch to the master branch.
Now i have this error : 

"org.shredzone.acme4j.exception.AcmeRateLimitExceededException: Error creating new authz :: too many currently pending authorizations"

**Comment by tazjin** [comment]
Your cluster should have a container engine service account to which you can attach the required permissions.

Alternatively you can create a separate service account with the needed permission, mount the token via (for example) a `Secret` and point the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the token file path.

If you want to use the GKE service account, you should be able to check whether `gcloud dns` commands work after SSHing into the machine.

**Comment by TheMalloum** [comment]
Hi tazjin,

How can i find the container engine service account ?

Thanks for your reactivity

**Comment by tazjin** [comment]
It should be listed under your projects IAM configuration and marked "Container Engine service account", you can also SSH into container engine instances and check with the `gcloud` utility (though I'm not sure what the exact command is, you'd have to look that up).

You can read more about [service accounts](https://cloud.google.com/compute/docs/access/service-accounts) on compute instances in the GCP documentation, but supporting it in detail is a bit out of the scope of what I can do - sorry!
