### ISSUE TITLE
Influence the cert filenames

### ISSUE THREAD

**Issue by ensonic** [tazjin/kubernetes-letsencrypt#70]
I am trying to use this with https://github.com/kubernetes/ingress/blob/master/controllers/gce/README.md#frontend-https

In https://github.com/tazjin/kubernetes-letsencrypt#usage you write:
```
The certificate secret will contain four files named certificate.pem, chain.pem, key.pem and fullchain.pem. You can mount these into whatever application you use to terminate TLS.
```

Unfortunately GCE expects the files to be called tls.crt and tls.key. This is not a bug on kubernetes-letsencrypt as such, just mention it here to hear your thoughts.

**Comment by tazjin** [comment]
Hey,

you can already override certificate filenames by setting environment variables: https://github.com/tazjin/kubernetes-letsencrypt/blob/v1.7/src/main/kotlin/in/tazj/k8s/letsencrypt/util/EnvironmentalConfiguration.kt#L28

I should probably document this more prominently :-)

**Comment by ensonic** [comment]
Awesome, I'll let you know how it goes. FYI: A lot of kubernets examples that involve self-signed certs use:
```
kubectl create secret tls foo-secret --key /tmp/tls.key --cert /tmp/tls.crt
```

**Comment by ensonic** [comment]
Oh my, it is already in the README. Sorry for the noise.
