### ISSUE TITLE
Add support for ingress controller secret format

### ISSUE THREAD

**Issue by sharebear** [tazjin/kubernetes-letsencrypt#71]
It would be nice if the secrets output by this controller were usable by the Ingress controller

From: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

> The TLS secret must contain keys named tls.crt and tls.key that contain the certificate and private key to use for TLS

**Comment by tazjin** [comment]
Hey,

this is supported, you can influence the filenames with environment variables documented [here](https://github.com/tazjin/kubernetes-letsencrypt#usage).

**Comment by sharebear** [comment]
Meh, sorry, it seems the formatting was just a little too subtle that I noticed it when skimming the doc.
