### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by chrisabrams** [tazjin/kubernetes-letsencrypt#82]
I've got multiple sites that are not renewing to lets encrypt anymore :/

**Comment by tazjin** [comment]
Hey!

We still use this for provisioning certificates without issue. This is not an official Let's Encrypt project though.

Do you receive some sort of error output from the controller?

**Comment by chrisabrams** [comment]
Nope. Just a lot of `Starting reconciliation loop for namespace...` but the certs are not expiring. We have not touched this in a very long time. It was auto renewing until, it wasn't :O

**Comment by chrisabrams** [comment]
Whoops didn't mean to close.

**Comment by chrisabrams** [comment]
Anyway to force the certs to renew?

**Comment by tazjin** [comment]
You could create a mismatch in the domain annotation on the existing certs, I'm not sure why it would stop renewing though 🤔

**Comment by chrisabrams** [comment]
What do you mean mismatch?

**Comment by chrisabrams** [comment]
I've got three domains in two different clusters that aren't renewing.

**Comment by tazjin** [comment]
I'm wondering if something changed with the library I use for the actual ACME-protocol implementation ... either way the reconciliation loop should still start running and fail further down the line.

Can you check if the `acme/expiryDate` annotation is present on the secrets?

> What do you mean mismatch?

There's an annotation on each `Secret` that contains the list of domains the certificate was issued for. If you add or remove an entry from that list the controller should want to renew the certificate regardless of the expiration date.

**Comment by chrisabrams** [comment]
They all have expiration dates far from now. I will try removing them to see what happens.

**Comment by tazjin** [comment]
Removing the expiration dates probably won't help (it may issue warnings), but changing the domain annotation should.

**Comment by chrisabrams** [comment]
Oh I see, remove the entire annotation from the secret? Will try that.

**Comment by tazjin** [comment]
Removing it will get you [this](https://github.com/tazjin/kubernetes-letsencrypt/blob/master/src/main/kotlin/in/tazj/k8s/letsencrypt/kubernetes/SecretManager.kt#L120), but if you put data in there that *doesn't match* the requested certificates (on your service annotation) reconciliation will be triggered.

**Comment by chrisabrams** [comment]
I removed all three annotations from the secret and got an error, but it did not regenerate.

**Comment by chrisabrams** [comment]
Still hasn't renewed :O

**Comment by tazjin** [comment]
Did you set up an annotation with a mismatching list of domains like I suggested?

**Comment by chrisabrams** [comment]
I still don't know what you mean by "mismatch", could you please provide an example?

**Comment by tazjin** [comment]
Assuming your certificate annotation requests domains for `foo.com, bar.com` the controller will add an annotation to the secrets that mentions these domains.

If you remove one of the domains from that annotation (on the secret), or add an extra one, they will no longer match what's expected and the reconciliation loop will be forced to run.

**Comment by chrisabrams** [comment]
Yes I ended up removing all the annotation pieces related to this project from a domain. It still did not renew.

**Comment by tazjin** [comment]
As mentioned [here](https://github.com/tazjin/kubernetes-letsencrypt/issues/82#issuecomment-358475277) *removing* the annotation will issue a warning, which is different from a data mismatch.

Earlier versions (before SAN-support was added) did not have this annotation at all, which is why that's not considered an error.

**Comment by chrisabrams** [comment]
Help me out here: "If you remove one of the domains from that annotation (on the secret), or add an extra one, they will no longer match what's expected and the reconciliation loop will be forced to run."

I removed the annotation, but now you are saying: "As mentioned here removing the annotation will issue a warning, which is different from a data mismatch."

Which is it? Should I be removing (sounds like no) or I should instead just change the domain name?

What if I just delete the secret?

**Comment by tazjin** [comment]
I'm distinguishing between deleting the *annotation itself* and modifying the *contents of* the annotation.

Deleting the secret also works, though.

**Comment by tazjin** [comment]
Did you get it to work?
