### ISSUE TITLE
No pom.xml?

### ISSUE THREAD

**Issue by f-f** [tazjin/kubernetes-letsencrypt#83]
Running `mvn package` results in maven rightfully complaining about no `pom.xml` file: 
`The goal you specified requires a project to execute but there is no POM in this directory`.

Moreover, there is a `gradle` configuration in the repo.

I guess build/package/docker-push instructions in `README` should be updated?

**Comment by tazjin** [comment]
Yes, the project moved to Gradle so the README is outdated atm.
